In [1]:
import numpy as np
import pandas as pd
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [10]:
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)
len(apartment)

5

In [12]:
t=np.array([2000,3000,2500])
t*72

array([144000, 216000, 180000])

In [14]:
#1.4
a=np.array([4,5])
b=np.array([2,1])
c=np.array([1,0])
a*2+b*(-3)+c*5

array([7, 7])

In [16]:
x=np.array([3,4,5,9])
y=np.array([1,5,3,6])
x*-200+y*400

array([-200, 1200,  200,  600])

In [3]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [12]:
m=Hut_Paradise_DF.values
m

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

In [29]:
#1.7
print(m[4])
print(m[:,3])
print(m[2,3])
print(len(m[:,0]))
print(m[:,1]-m[:,5])
print(m[:,0]*100*4/1000)
l=np.array([10,20,30,15,5,40,20,8,20])
l=l.transpose()
print(m[:,4]@l)

[40 33  1  6 20 16]
[ 5 12 10  3  6 13  8 21  5]
10
9
[13 12 15 13 17  9 20 15 25]
[26. 28. 48. 14. 16. 20. 40. 36. 34.]
1348


In [40]:
#1.7.
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
print(v*2+w*-3)
print((v*2+w*-3)@u)
unorm=np.linalg.norm(u)
print(u/unorm)
vnorm=np.linalg.norm(v)
print(v/vnorm)
wnorm=np.linalg.norm(w)
print(w/wnorm)

[-3 14  3  4  2]
0
[0.8660254  0.         0.28867513 0.28867513 0.28867513]
[ 0.          0.33333333  0.          0.66666667 -0.66666667]
[ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]


In [41]:
#1.10
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [43]:
Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [44]:
Cons=np.array([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [47]:
print(Inc*0.87)
print(Inc*0.87-Cons)

[[ 87.  130.5  78.3]
 [191.4 174.   69.6]
 [121.8 113.1  87. ]]
[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


In [51]:
a=np.matrix('1,-1,2,4,0;8,2,0,5,3;0,1,2,1,2')
b=np.matrix('1,0,1,0;0,0,2,-1;1,0,1,1;0,1,1,1;1,1,0,-1')
a*b

matrix([[ 3,  4,  5,  7],
        [11,  8, 17,  0],
        [ 4,  3,  5,  0]])

In [64]:
#1.14
a=np.matrix('1,1')
b=np.matrix('2,-1')
c=np.matrix('1,2')
c*c.T

matrix([[5]])

In [2]:
#1.15
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [11]:
A@x

array([26, 30])

In [12]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

In [13]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [14]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [27]:
m=np.array([x,y,z])
print(m)
print(m.T)

[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]]
[[ 1  2 -1]
 [ 2  1  1]
 [ 1 -1 -1]
 [ 0  1  0]
 [ 4  0  0]]


In [28]:
m@m.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [29]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [32]:
count=Count_DF.values
price=Price_DF.values


array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [33]:
count*price

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [36]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]
com=np.array(com)
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [52]:
ben=(count*price)@com
ben

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [53]:
(count*price)@(np.ones(5)-com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [60]:
a=np.array([[1,0,0],[0,4,0],[0,0,5]])
np.linalg.inv(a)

array([[1.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.2 ]])

In [61]:
a=np.array([[1,2],[1,1]])
b=np.array([[5,-2],[-1,4]])

In [70]:
A=np.array([[2,0,0],[0,1,0],[0,0,4]])
np.linalg.det(np.linalg.inv(A))

0.12500000000000003

In [74]:
l=np.array([[1,0,3,5],[0,4,5,5],[0,0,0,4],[0,0,0,0]])
np.linalg.matrix_rank(l)

3

In [75]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

In [76]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [78]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
tot=np.array([v1,v2,v3,v4])
tot

array([[ 9, 10,  7,  7,  9],
       [ 2,  0,  5,  1,  4],
       [ 4,  0,  0,  4,  1],
       [ 3, -4,  3, -1, -4]])

In [79]:
np.linalg.matrix_rank(tot)

4

In [81]:
gr=tot@tot.T
gr

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [83]:
np.linalg.det(gr)

3716647.9999999995

In [84]:
np.linalg.inv(gr)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])